FromZoid.VOICES = {
	Vlad = {
		"Let me in, I have vodka.",
		"Come. We drink. Then we talk.",
		"Is cold like grave out here, friend.",
		"I brought the good bottle. Not the cheap one.",
		"Open a little. I pour through the crack.",
		"You leave me with the night? This is rude.",
		"I am not stranger. I am thirsty gentleman.",
		"The sun is dead. Now we live properly.",
		"One glass. You will sleep like baby.",
		"I can smell your heat through the wood.",
		"Do not make me wait. Waiting makes me… impolite.",
		"I had house once. Nice house. Then morning came.",
		"Please. My hands are shaking.",
		"You think the door is your friend. Door is just wood.",
		"I will not break it. I have manners. Open it.",
		"Share the dark with me. Is not so lonely.",
		"I left my coat in another year. Let me in.",
		"Listen. No footsteps but mine. Safe. Safe.",
		"You are kind person. Kind persons open doors.",
		"If you do not open, I sit here until you rot.",
		"Vodka first. Blood later. Joke. Joke.",
		"My village taught me: guest who knocks is guest.",
		"I see the candle. Put it out. Come to the latch.",
		"Open, little host. I brought enough for two throats.",
	},
	Miles = {
		"Knock knock, little house. Guess who brought the dessert.",
		"Stir the pot and count to ten / lock the latch and do it again / I know a secret, you know it too / the night came early just for you.",
		"Come on. The show’s no fun with the curtain shut.",
		"I can hear you holding your breath. That’s adorable.",
		"Two little shutters, one little hall / three little heartbeats hiding from it all / I brought a smile, I brought a knife / open up, sugar, and get a life.",
		"Don’t be shy. Shy meat goes tough.",
		"I wrote you a song. It’s very short. It ends when you scream.",
		"Round we go around the block / tick tock tick, don’t watch the clock / if you’re in there, I’m out here / that’s the whole joke, my dear.",
		"Peek through the keyhole. I already am.",
		"You missed the parade. I brought it to your porch.",
		"Hush little house don’t you cry / if you don’t open I know why / I’ll wait, I’ll wait, I’ll wait some more / there’s always a hinge, there’s always a door.",
		"Bravo for the boards. Encore for the screaming.",
		"I don’t need a ticket. You are the ticket.",
		"Knives in the drawer, pies in the sky / everybody’s hungry by and by / clap your hands, stamp your feet / the night is sweet, the night is sweet.",
		"Say something. I’ll turn it into a punchline.",
		"Your lights are cheating. Cheaters get a private show.",
		"One for the window, two for the floor / three for the one who won’t open the door / four for the morning that never comes back / five for the laugh in the pitch-black.",
		"I’m not mad. I’m booked solid. You’re tonight.",
		"Open up. I left my manners in the funhouse.",
		"Dance on the porch till the boards complain / rattle the glass, remember my name / Miles at your service, Miles at your throat / that’s the last verse, that’s all she wrote.",
		"If you stay quiet I get louder. That’s the rule.",
		"I brought no flowers. I brought an appetite.",
		"Hide little rabbit, hide little mouse / I know every corner of this little house / when the chorus hits, you better sing / or I’ll finish the number without you in.",
		"Last call for volunteers. That’s you. That’s always you.",
	},
	Knox = {
		"I will feed you your spleen, you uncivilized swine.",
		"I can see you. Do not insult me by crouching.",
		"Draw the curtain if you like. I already have your measure.",
		"This window is a disappointing fortress.",
		"Come to the glass. I want you to watch your own decision.",
		"You are not clever. You are merely indoors.",
		"I shall have the fingers that hold that latch.",
		"Hide under the sill. Animals do that.",
		"When this pane goes, so do your pretenses.",
		"I have all night. You have a bladder and a pulse.",
		"Look at me. Cowards die with their eyes shut anyway.",
		"Your breathing fogs the glass. Charming. Loud.",
		"I will unmake you in the order you were assembled.",
		"Do not wave. I am not your neighbor.",
		"That board will not save the meat behind it.",
		"Step closer. I want the satisfaction of your face.",
		"You will open, or you will be opened. Grammar, not mercy.",
		"I can wait until your candle dies. I enjoy the dark.",
		"Speak up. I dislike mumbling through windows.",
		"I will take the tongue that will not answer.",
		"Civilization ends at your threshold. I am here to collect it.",
		"Keep staring. I am patient with slow livestock.",
		"If you sleep, I will still be in the glass.",
		"Good night. Try not to dream of the morning. There isn’t one.",
	},
	Roxie = {
		"Come on, let me in. Let’s warm up together.",
		"You sound tired. I could fix that.",
		"I saw your light. It looks good on you.",
		"Just the latch. I’m freezing in this dress.",
		"You don’t have to be brave. You just have to open.",
		"I bet you’re kinder than you think. Kind people open doors.",
		"Let me in. I’ll keep you company till the sun… whenever.",
		"Your house smells like safety. I miss that.",
		"Don’t leave me with the quiet. The quiet bites.",
		"I could whisper you to sleep. Inside.",
		"You’re shaking. I can hear it. Come here.",
		"One minute. One door. Then you can decide I’m a mistake.",
		"I brought nothing but me. That’s the generous version.",
		"Unlock it. I’ll do the rest slowly.",
		"You kept this place so nice. Let me see it.",
		"I’m not like the knocking. I’m like a guest.",
		"Please. My teeth are chattering. That’s all.",
		"If you open, I promise I won’t scream. You might.",
		"Stay by the door. I want your voice closer.",
		"Warm room, warm hands, warm… everything. Come on.",
		"You’re allowed to want this. I already do.",
		"The night is long. We could make it shorter.",
		"I can be so sweet if you let me past the wood.",
		"Open up, honey. I’ll be gentle until I’m not.",
	},
	Annie = {
		"Have you seen my parents?",
		"I’m not supposed to be out after dark.",
		"Please. I can’t find our house. This one looks like it.",
		"Mom said knock and wait. I waited.",
		"I’m cold. Can I stand inside just until they come?",
		"I won’t touch anything. I promise.",
		"There were people in the street. They smiled too wide.",
		"If you’re hiding, I can hide too. I’m good at it.",
		"Please don’t leave me on the porch.",
		"I have a key. It doesn’t work. Maybe yours does.",
		"Dad always opens when I count to three. One… two…",
		"I’m not a stranger. I’m Annie. They’ll tell you.",
		"The night keeps moving. I need a still room.",
		"Can you call them? I forgot the number.",
		"I’ll sit by the door. You won’t even see me.",
		"Something scratched the other house. This one still looks safe.",
		"I’m hungry. I won’t eat much.",
		"If you see a woman in a blue coat, that’s Mom. Tell her I’m here.",
		"Please. My flashlight died.",
		"I heard you walking. Living people walk like that.",
		"I don’t like the singing man. Let me in before he comes back.",
		"I can sleep on the floor. I brought my own quiet.",
		"Open a little. I’ll squeeze. I’m little.",
		"If you don’t open, I’ll still wait. That’s what good girls do.",
	},
	Zelda = {
		"Knock knock. Who’s there?",
		"It smells nice in there. Are you cooking a pie?",
		"If a house has a mouth, should it chew or smile?",
		"I brought a secret. It doesn’t fit under the door.",
		"Three knocks for luck. Four knocks for later. I did five.",
		"What’s black and white and red all over the porch?",
		"Let me in and I’ll tell you how windows get teeth.",
		"The moon is a key. You are a lock. I am tired of metaphors.",
		"Knock knock. It’s me. It’s also not.",
		"Are you counting sheep or counting doors?",
		"I lost my shadow. Can I borrow yours till morning?",
		"Hot pie, cold hands, open latch, understand?",
		"If I say please twice, does the wood get kinder?",
		"Someone’s cooking. Someone’s breathing. Someone’s lying.",
		"Knock knock. House. House who? That’s the whole name.",
		"I’ll trade you a riddle for a hinge.",
		"Why did the girl wait all night? To see if you were real.",
		"Sugar on the sill. Salt on the step. You in the middle.",
		"Open up and I’ll stop asking who.",
		"The pie is a trick. The knock is a trick. I’m the leftover.",
		"Knock knock. Guess. No, don’t guess. Open.",
		"If you dream about me, leave the door unlocked. Fair?",
		"I know a song with no words. The chorus is your heartbeat.",
		"Knock knock. Who’s there? Zelda. Zelda who? Zelda in.",
	},
}
